// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MathematicsUIClient is the client API for MathematicsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MathematicsUIClient interface {
	// ListEngineSpecs returns a list of Mathematics Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (MathematicsUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type mathematicsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewMathematicsUIClient(cc grpc.ClientConnInterface) MathematicsUIClient {
	return &mathematicsUIClient{cc}
}

func (c *mathematicsUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (MathematicsUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MathematicsUI_ServiceDesc.Streams[0], "/v1.MathematicsUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &mathematicsUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MathematicsUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type mathematicsUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *mathematicsUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mathematicsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.MathematicsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MathematicsUIServer is the server API for MathematicsUI service.
// All implementations must embed UnimplementedMathematicsUIServer
// for forward compatibility
type MathematicsUIServer interface {
	// ListEngineSpecs returns a list of Mathematics Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, MathematicsUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedMathematicsUIServer()
}

// UnimplementedMathematicsUIServer must be embedded to have forward compatible implementations.
type UnimplementedMathematicsUIServer struct {
}

func (UnimplementedMathematicsUIServer) ListEngineSpecs(*ListEngineSpecsRequest, MathematicsUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedMathematicsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedMathematicsUIServer) mustEmbedUnimplementedMathematicsUIServer() {}

// UnsafeMathematicsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MathematicsUIServer will
// result in compilation errors.
type UnsafeMathematicsUIServer interface {
	mustEmbedUnimplementedMathematicsUIServer()
}

func RegisterMathematicsUIServer(s grpc.ServiceRegistrar, srv MathematicsUIServer) {
	s.RegisterService(&MathematicsUI_ServiceDesc, srv)
}

func _MathematicsUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MathematicsUIServer).ListEngineSpecs(m, &mathematicsUIListEngineSpecsServer{stream})
}

type MathematicsUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type mathematicsUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *mathematicsUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _MathematicsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MathematicsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.MathematicsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MathematicsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MathematicsUI_ServiceDesc is the grpc.ServiceDesc for MathematicsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MathematicsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.MathematicsUI",
	HandlerType: (*MathematicsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _MathematicsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _MathematicsUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mathematics-ui.proto",
}
